### ISSUE TITLE
Mocking libraries

### ISSUE THREAD

**Issue by consal** [kvas-it/pytest-console-scripts#28]
Hi,

I have a question - how can I mock something that I test via `script_runner`?
I know it's meant for integration tests, but sometimes it's useful...

I mean my script does an import that I'd like to mock, for example, `import requests`

Cheers!

**Comment by kvas-it** [comment]
Hi @consal!

You can mock things out in the code that runs under `script_runner` using the normal approach (see [monkeypatch fixture](https://docs.pytest.org/en/latest/monkeypatch.html) and [pytest-mock plugin](https://github.com/pytest-dev/pytest-mock)), however, this will only work in `inprocess` mode, when the console script is run in the same process as the test (see [README](https://github.com/kvas-it/pytest-console-scripts#configuring-script-execution-mode) for more info). Inprocess mode has some limitations (e.g. #24) but if your tests work in it, then mocking will just work as normal.

In `subprocess` mode mocking won't work because there the script under test runs in a separate Python process that `pytest-console-scripts` has no control over other than launching it.

Cheers,
Vasily
