### ISSUE TITLE
Testing scripts which trigger user input

### ISSUE THREAD

**Issue by HealthyPear** [kvas-it/pytest-console-scripts#58]
Is there a way to mock an stdin from command line?

say I have a script with an entry point defined which behaves like this:

- if I call `my-cli-tool` with no arguments it triggers the user to inject some info (say a,b,c)
- if I call it as `my-cli-tool --a some_thing --b some_other_thing --c a_different_thing` it just works

I have tried naïvely to test this as

```python
def test_my_cli_tool(script_runner):
    result = script_runner.run(
        "my-cli-tool",
        "--a 'some_thing'",
        "--b 'some_other_thing'",
        "--c 'a_different_thing'",
    )

    assert result.success
    assert result.stderr == ""
```

but it fails because it expects an input from the user even if I already set the flag.

It's like it is running first `my-cli-tool` with no arguments first.

**Comment by HealthyPear** [comment]
Also, using subprocess mode doesn't fix it

**Comment by kvas-it** [comment]
Hi @HealthyPear.

The option argument is normally a separate item in the argument list from the option itself. Try to run it like this:

    result = script_runner.run(
        "my-cli-tool",
        "--a", "some_thing",
        "--b", "some_other_thing",
        "--c", "a_different_thing",
    )

hopefully it will work as you expect.

**Comment by HexDecimal** [comment]
Another option is that the CLI likely supports `--key=value` syntax, so this might look better:
```py
result = script_runner.run(
    "my-cli-tool",
    "--a=some_thing",
    "--b=some_other_thing",
    "--c=a_different_thing",
)
```
> Also, using subprocess mode doesn't fix it

Subprocess mode won't work because the arguments that were given were malformed.  However, it's likely that subprocess mode with the option `shell=True` will work for that input, but it's not a good habit to rely on that.

Keep in mind that CLI arguments are not the same as stdin.  Command line arguments go to `sys.argv` and not `sys.stdin`.

**Comment by HexDecimal** [comment]
Since the 1.4.0 release the following will also work:
```py
result = script_runner.run(
    "my-cli-tool --a some_thing --b some_other_thing --c a_different_thing",
    shell=True,
)
```
This lets you test the command as if you ran it from the shell. So you can simply copy your shell commands without having to know how to split them into arguments.

Since this issue is that `"--a 'some_thing'"` was a malformed argument there isn't really any more to add.  There's nothing to fix in the library. Feel free to ask if you have any more questions.
